import Head from "next/head";
import Page from "@/components/layout/Page";
import { useSession } from "next-auth/react";
import CustomerList from "@/components/profile/organisms/profileAdmin/CustomerList";

export default function ProfilePage() {
  // const ctx = useAppData()
  // console.log(ctx)'

  const { data: session } = useSession();
  const role = session?.role;

  return (
    <>
      <Head>
        <title>Lista de clientes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page>
        {role === "ADMIN" ? <CustomerList /> : <div>Não autorizado!</div>}
      </Page>
    </>
  );
}
