import Head from "next/head";
import Login from "@/components/login/Login";
import Page from "@/components/layout/Page";
import { useSession } from "next-auth/react";
import Router from "next/router";
import Image from "next/image";

export default function LoginPage() {
  const { data: session } = useSession();

  if (session) {
    Router.push(`/profile?id=${session?.user?.id}`);
    return;
  } else {
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <Page extern>
            <div style={{}}>
              <Image
                src="/loginPageImage.png"
                alt="vector"
                width={580}
                height={500}
                priority={true} 
              />
            </div>
            <Login />
          </Page>
        </main>
      </>
    );
  }
}
