import Head from "next/head";
import LoginPage from "@/components/login/LoginPage";
import Page from "@/components/layout/Page";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Page extern>
          <LoginPage />
        </Page>
      </main>
    </>
  );
}
