import Head from "next/head";
import Page from "@/components/layout/Page";
import Profile from "@/components/profile/Profile";
import { GetServerSideProps } from "next";

export default function ProfilePage() {
  return (
    <>
      <Head>
        <title>Perfil</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page>
        <Profile />
      </Page>
    </>
  );
}
