import Head from "next/head";
import Page from "@/components/layout/Page";
import Profile from "@/components/profile/Profile";
import ProfileAdmin from "@/components/profile/ProfileAdmin"
import useAppData from "@/data/hooks/useAppContext";
import { useSession } from "next-auth/react";

export default function ProfilePage() {
  // const ctx = useAppData()
  // console.log(ctx)

  const { data: session } = useSession()
  const role = session?.role

  return (
    <>
      <Head>
        <title>Perfil</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page>
        {role === 'ADMIN' ? <ProfileAdmin /> : <Profile />}
      </Page>
    </>
  );
}
