import Head from "next/head";
import Page from "@/components/layout/Page";
import { useSession } from "next-auth/react";
import UserCodesProviderView from "@/components/profile/UserCodesProviderView";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { Users } from "@prisma/client";
import ClientOverview from "@/components/profile/organisms/profile/ClientOverview";


export default function ProfileOverview() {
  // const ctx = useAppData()
  // console.log(ctx)'

  const { data: session } = useSession();
  const role = session?.role;
  const [user, setUser] = useState<Users>();
  const [loading, setLoading] = useState<boolean>(true);

  const {
    query: { id },
  } = useRouter();

  useEffect(() => {
    fetch(`/api/users?id=${id}`)
      .then((data) => data.json())
      .then(setUser)
      .then(() => setLoading(false));
  }, [id]);

  console.log(user)

  return (
    <>
      <Head>
        <title>Perfil usuário</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page>
        <ClientOverview user={user}/>
      </Page>
    </>
  );
}
