import Head from "next/head";
import Page from "@/components/layout/Page";

export default function Protected() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page>
        <h1>Protected</h1>
      </Page>
    </>
  );
}
