import Head from "next/head";
import Register from "@/components/login/Register";
import Page from "@/components/layout/Page";
import { useSession } from "next-auth/react";
import Router from "next/router";
import AsideImage from "@/components/login/AsideImage";
import { useState } from "react";

export default function RegisterPage() {
  const [id, setId] = useState("");
  const { data: session } = useSession();
  //session.user.provider

  // ta salvando o usuário do google no mongo, mas ta dando algum erro

  if (session?.user.provider === "credentials") {
    Router.push(`/profile?id=${session?.user.id}`);
    return;
  } else {
    return (
      <>
        <Head>
          <title>Register</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Page extern>
          <div
            style={{
              display: "flex",
              boxShadow:
                "0 1px 4px rgba(0, 0, 0, 0.05), 0 4px 16px rgba(0, 0, 0, 0.06)",
              margin: "30px",
            }}
          >
            <AsideImage />
            <Register />
          </div>
        </Page>
      </>
    );
  }
}
